"""Public simulation API."""

from .adapter import (
    NEURAL_PA_OUTCOME_TO_INDEX,
    NEURAL_PA_OUTCOMES,
    TERMINAL_TO_NEURAL_TARGET,
    AdaptedPlateAppearanceProbabilityModel,
    BattedBallOutSplit,
    NeuralPlateAppearanceProbabilitySource,
    NeuralTerminalAdapterConfig,
    NeuralTerminalProbabilityAdapter,
    neural_training_target,
    neural_training_target_index,
    terminal_state_bucket,
)
from .events import (
    FuturePlateAppearanceContext,
    ObservedPlateAppearance,
    SimulatedPlateAppearance,
    TerminalPlateAppearanceEvent,
)
from .probability import (
    DEFAULT_EVENT_PRIOR,
    EmpiricalPlateAppearanceProbabilityModel,
    EventProbabilities,
    PlateAppearanceProbabilityModel,
    StaticPlateAppearanceProbabilityModel,
    normalize_event_probabilities,
    sample_terminal_event,
)
from .simulator import (
    GameEndReason,
    GameSimulationSpec,
    GameSimulator,
    HitScenario,
    PitchingPlan,
    SimulationBatch,
    SimulationLimitError,
    SimulationOutcome,
    TeamLineup,
    combine_hit_scenarios,
)
from .state import BaseRunners, GameState, HalfInning
from .transition import (
    RunnerAdvancementRates,
    StateTransitionEngine,
    TransitionResult,
)

__all__ = [
    "NEURAL_PA_OUTCOMES",
    "NEURAL_PA_OUTCOME_TO_INDEX",
    "TERMINAL_TO_NEURAL_TARGET",
    "AdaptedPlateAppearanceProbabilityModel",
    "BattedBallOutSplit",
    "DEFAULT_EVENT_PRIOR",
    "BaseRunners",
    "EmpiricalPlateAppearanceProbabilityModel",
    "EventProbabilities",
    "FuturePlateAppearanceContext",
    "GameEndReason",
    "GameSimulationSpec",
    "GameSimulator",
    "GameState",
    "HalfInning",
    "HitScenario",
    "ObservedPlateAppearance",
    "PitchingPlan",
    "PlateAppearanceProbabilityModel",
    "NeuralPlateAppearanceProbabilitySource",
    "NeuralTerminalAdapterConfig",
    "NeuralTerminalProbabilityAdapter",
    "RunnerAdvancementRates",
    "SimulatedPlateAppearance",
    "SimulationBatch",
    "SimulationLimitError",
    "SimulationOutcome",
    "StateTransitionEngine",
    "StaticPlateAppearanceProbabilityModel",
    "TeamLineup",
    "TerminalPlateAppearanceEvent",
    "TransitionResult",
    "combine_hit_scenarios",
    "normalize_event_probabilities",
    "neural_training_target",
    "neural_training_target_index",
    "sample_terminal_event",
    "terminal_state_bucket",
]
