"""Runnable, source-neutral prediction pipelines."""

from .kbo_live_hit_baseline import (
    LIVE_HIT_CANONICAL_SQL,
    LIVE_HIT_FEATURE_NAMES,
    LIVE_HIT_LABELS,
    CanonicalPlateAppearanceRow,
    LiveHitFeatureDataset,
    build_live_hit_fixed_season_splits,
    build_pregame_live_hit_dataset,
    evaluate_live_hit_fixed_season_catboost,
    evaluate_live_hit_fixed_season_catboost_json,
    reduce_player_game_live_hit_targets,
)
from .kbo_match_baseline import (
    FIXED_SEASON_EVALUATIONS,
    HOME_RESULT_LABELS,
    MATCH_FEATURE_NAMES,
    CanonicalGameRow,
    FixedSeasonEvaluation,
    MatchFeatureDataset,
    SeasonDatasetSplit,
    build_fixed_season_splits,
    build_pregame_match_dataset,
    canonicalize_game_rows,
    evaluate_fixed_season_catboost,
    evaluate_fixed_season_catboost_json,
    render_evaluation_json,
)

__all__ = [
    "FIXED_SEASON_EVALUATIONS",
    "HOME_RESULT_LABELS",
    "LIVE_HIT_CANONICAL_SQL",
    "LIVE_HIT_FEATURE_NAMES",
    "LIVE_HIT_LABELS",
    "MATCH_FEATURE_NAMES",
    "CanonicalGameRow",
    "CanonicalPlateAppearanceRow",
    "FixedSeasonEvaluation",
    "MatchFeatureDataset",
    "LiveHitFeatureDataset",
    "SeasonDatasetSplit",
    "build_fixed_season_splits",
    "build_live_hit_fixed_season_splits",
    "build_pregame_live_hit_dataset",
    "build_pregame_match_dataset",
    "canonicalize_game_rows",
    "evaluate_fixed_season_catboost",
    "evaluate_fixed_season_catboost_json",
    "evaluate_live_hit_fixed_season_catboost",
    "evaluate_live_hit_fixed_season_catboost_json",
    "reduce_player_game_live_hit_targets",
    "render_evaluation_json",
]
