"""Generate the complete path-and-source handoff used for external code review."""

from __future__ import annotations

import re
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = PROJECT_ROOT / "code_summary.md"

ROOT_FILES = (
    ".env.example",
    ".gitattributes",
    ".gitignore",
    "LICENSE.md",
    "pyproject.toml",
    "README.md",
)
SOURCE_DIRECTORIES = (".github", "requirements", "scripts", "src", "tests")
IGNORED_PARTS = {
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
}
LANGUAGE_BY_SUFFIX = {
    ".md": "markdown",
    ".py": "python",
    ".sh": "bash",
    ".txt": "text",
    ".toml": "toml",
}
LANGUAGE_BY_NAME = {
    ".env.example": "dotenv",
    ".gitignore": "gitignore",
}


def _included_files() -> tuple[Path, ...]:
    files = [PROJECT_ROOT / name for name in ROOT_FILES]
    for directory_name in SOURCE_DIRECTORIES:
        directory = PROJECT_ROOT / directory_name
        files.extend(
            path
            for path in directory.rglob("*")
            if path.is_file()
            and not any(part in IGNORED_PARTS for part in path.relative_to(PROJECT_ROOT).parts)
        )
    unique = {path.resolve(): path for path in files if path.is_file()}
    return tuple(
        sorted(
            unique.values(),
            key=lambda path: path.relative_to(PROJECT_ROOT).as_posix(),
        )
    )


def _fence_for(text: str) -> str:
    longest = max((len(match.group(0)) for match in re.finditer(r"`+", text)), default=0)
    return "`" * max(4, longest + 1)


def build_summary() -> str:
    sections = [
        "<!-- Generated by scripts/build_code_summary.py for external code review. -->",
        "<!-- Each H1 is one project-relative path followed by the complete file content. -->",
        "",
    ]
    for path in _included_files():
        relative = path.relative_to(PROJECT_ROOT).as_posix()
        content = path.read_text(encoding="utf-8")
        fence = _fence_for(content)
        language = LANGUAGE_BY_NAME.get(path.name, LANGUAGE_BY_SUFFIX.get(path.suffix, "text"))
        sections.extend(
            (
                f"# `{relative}`",
                "",
                f"{fence}{language}",
                content.rstrip("\n"),
                fence,
                "",
            )
        )
    return "\n".join(sections).rstrip() + "\n"


def main() -> None:
    OUTPUT_PATH.write_text(build_summary(), encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT_PATH} ({OUTPUT_PATH.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
